language: swift
osx_image: xcode10
before_script:
    - gem install fastlane --no-ri --no-rdoc --no-document
    - npm install -g danger
    - brew install danger/tap/danger-swift
    - danger process danger-swift
    - swiftlint lint
      
script:
    - xcodebuild clean test -project ASLocalizeBetter.xcodeproj -scheme ASLocalizeBetter -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
     
matrix:
 fast_finish: true
 include:
 - osx_image: xcode10
   env: CI_BUILD_TARGET='nap' CI_DEVICE='iPhone X (12.0)'
