"language": "swift"
"osx_image": "xcode10"
"before_script":
    - bundle exec danger
"script":
    - xcodebuild clean test -project ASLocalizeBetter.xcodeproj -scheme ASLocalizeBetter -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
